name: Tests

on: ['push', 'pull_request']

env:
  COMPOSER_ROOT_VERSION: 1.x-dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ['7.3', '7.4', '8.0']
        dependency-version: [prefer-lowest, prefer-stable]
        coverage-driver: [pcov, xdebug]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }} - ${{ matrix.coverage-driver }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: ${{ matrix.coverage-driver }}

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP 7 dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
      if: "matrix.php < 8"

    - name: Install PHP 8 dependencies
      run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress
      if: "matrix.php >= 8"

    - name: Unit Tests
      run: ./vendor/bin/pest --colors=always --coverage
